package ru.snatcher.hieronymus.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig translateDaoConfig;
    private final DaoConfig languageDaoConfig;

    private final TranslateDao translateDao;
    private final LanguageDao languageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        translateDaoConfig = daoConfigMap.get(TranslateDao.class).clone();
        translateDaoConfig.initIdentityScope(type);

        languageDaoConfig = daoConfigMap.get(LanguageDao.class).clone();
        languageDaoConfig.initIdentityScope(type);

        translateDao = new TranslateDao(translateDaoConfig, this);
        languageDao = new LanguageDao(languageDaoConfig, this);

        registerDao(Translate.class, translateDao);
        registerDao(Language.class, languageDao);
    }
    
    public void clear() {
        translateDaoConfig.clearIdentityScope();
        languageDaoConfig.clearIdentityScope();
    }

    public TranslateDao getTranslateDao() {
        return translateDao;
    }

    public LanguageDao getLanguageDao() {
        return languageDao;
    }

}
