package ru.snatcher.hieronymus.model.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Unique;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LANGUAGE".
 */
@Entity
public class Language {

    @Id
    @Unique
    private String LangKey;
    private String LangValue;

    @Generated
    public Language() {
    }

    public Language(String LangKey) {
        this.LangKey = LangKey;
    }

    @Generated
    public Language(String LangKey, String LangValue) {
        this.LangKey = LangKey;
        this.LangValue = LangValue;
    }

    public String getLangKey() {
        return LangKey;
    }

    public void setLangKey(String LangKey) {
        this.LangKey = LangKey;
    }

    public String getLangValue() {
        return LangValue;
    }

    public void setLangValue(String LangValue) {
        this.LangValue = LangValue;
    }

}
