package ru.snatcher.hieronymus.model.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LANGUAGE".
 */
@Entity
public class Language {

	@Id
	private String LangKey;

	@NotNull
	private String LangValue;

	@Generated
	public Language() {
	}

	public Language(String LangKey) {
		this.LangKey = LangKey;
	}

	@Generated
	public Language(String LangKey, String LangValue) {
		this.LangKey = LangKey;
		this.LangValue = LangValue;
	}

	public String getLangKey() {
		return LangKey;
	}

	public void setLangKey(String LangKey) {
		this.LangKey = LangKey;
	}

	@NotNull
	public String getLangValue() {
		return LangValue;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the database.
	 */
	public void setLangValue(@NotNull String LangValue) {
		this.LangValue = LangValue;
	}

}
