package ru.snatcher.hieronymus.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Unique;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LANGUAGE".
 */
@Entity
public class Language {

	@Id(autoincrement = true)
	private Long id;

	@Unique
	private String fLangKey;

	@Unique
	private String fLangValue;

	@Generated
	public Language() {
	}

	public Language(Long id) {
		this.id = id;
	}

	@Generated
	public Language(Long id, String fLangKey, String fLangValue) {
		this.id = id;
		this.fLangKey = fLangKey;
		this.fLangValue = fLangValue;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLangKey() {
		return fLangKey;
	}

	public void setLangKey(String fLangKey) {
		this.fLangKey = fLangKey;
	}

	public String getLangValue() {
		return fLangValue;
	}

	public void setLangValue(String fLangValue) {
		this.fLangValue = fLangValue;
	}

}
