package ru.snatcher.hieronymus.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "TRANSLATE".
 */
public class TranslateDao extends AbstractDao<Translate, Long> {

	public static final String TABLENAME = "TRANSLATE";

	public TranslateDao(DaoConfig config) {
		super(config);
	}


	public TranslateDao(DaoConfig config, DaoSession daoSession) {
		super(config, daoSession);
	}

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"TRANSLATE\" (" + //
				"\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
				"\"F_LANG\" TEXT," + // 1: fLang
				"\"F_TRANSLATED_TEXT\" TEXT UNIQUE ," + // 2: fTranslatedText
				"\"IS_BOOKMARK\" INTEGER);"); // 3: isBookmark
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRANSLATE\"";
		db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, Translate entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		String fLang = entity.getLang();
		if (fLang != null) {
			stmt.bindString(2, fLang);
		}

		String fTranslatedText = entity.getTranslatedText();
		if (fTranslatedText != null) {
			stmt.bindString(3, fTranslatedText);
		}

		Boolean isBookmark = entity.getIsBookmark();
		if (isBookmark != null) {
			stmt.bindLong(4, isBookmark ? 1L : 0L);
		}
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, Translate entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		String fLang = entity.getLang();
		if (fLang != null) {
			stmt.bindString(2, fLang);
		}

		String fTranslatedText = entity.getTranslatedText();
		if (fTranslatedText != null) {
			stmt.bindString(3, fTranslatedText);
		}

		Boolean isBookmark = entity.getIsBookmark();
		if (isBookmark != null) {
			stmt.bindLong(4, isBookmark ? 1L : 0L);
		}
	}

	@Override
	public Long readKey(Cursor cursor, int offset) {
		return cursor.isNull(offset) ? null : cursor.getLong(offset);
	}

	@Override
	public Translate readEntity(Cursor cursor, int offset) {
		Translate entity = new Translate( //
				cursor.isNull(offset) ? null : cursor.getLong(offset), // id
				cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // fLang
				cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // fTranslatedText
				cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // isBookmark
		);
		return entity;
	}

	@Override
	public void readEntity(Cursor cursor, Translate entity, int offset) {
		entity.setId(cursor.isNull(offset) ? null : cursor.getLong(offset));
		entity.setLang(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
		entity.setTranslatedText(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
		entity.setIsBookmark(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
	}

	@Override
	protected final Long updateKeyAfterInsert(Translate entity, long rowId) {
		entity.setId(rowId);
		return rowId;
	}

	@Override
	public Long getKey(Translate entity) {
		if (entity != null) {
			return entity.getId();
		} else {
			return null;
		}
	}

	@Override
	public boolean hasKey(Translate entity) {
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable() {
		return true;
	}

	/**
	 * Properties of entity Translate.<br/>
	 * Can be used for QueryBuilder and for referencing column names.
	 */
	public static class Properties {
		public final static Property Id = new Property(0, Long.class, "id", true, "_id");
		public final static Property FLang = new Property(1, String.class, "fLang", false, "F_LANG");
		public final static Property FTranslatedText = new Property(2, String.class, "fTranslatedText", false, "F_TRANSLATED_TEXT");
		public final static Property IsBookmark = new Property(3, Boolean.class, "isBookmark", false, "IS_BOOKMARK");
	}

}
