package ru.snatcher.hieronymus.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Unique;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TRANSLATE".
 */
@Entity
public class Translate {

	@Id(autoincrement = true)
	private Long id;
	private String fLang;

	@Unique
	private String fTranslatedText;
	private Boolean isBookmark;

	@Generated
	public Translate() {
	}

	public Translate(Long id) {
		this.id = id;
	}

	@Generated
	public Translate(Long id, String fLang, String fTranslatedText, Boolean isBookmark) {
		this.id = id;
		this.fLang = fLang;
		this.fTranslatedText = fTranslatedText;
		this.isBookmark = isBookmark;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLang() {
		return fLang;
	}

	public void setLang(String fLang) {
		this.fLang = fLang;
	}

	public String getTranslatedText() {
		return fTranslatedText;
	}

	public void setTranslatedText(String fTranslatedText) {
		this.fTranslatedText = fTranslatedText;
	}

	public Boolean getIsBookmark() {
		return isBookmark;
	}

	public void setIsBookmark(Boolean isBookmark) {
		this.isBookmark = isBookmark;
	}

}
